name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 1'

permissions:
  contents: read

jobs:
  chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.5
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Start ChromeDriver
        run: chromedriver --port=4444 &
      - run: flutter drive --driver test_driver/integration_test.dart --target integration_test/scroll_world_test.dart -d chrome
        working-directory: example

  android:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.5
          channel: stable
          cache: true
      - run: flutter pub get
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_6
          script: cd example && flutter test integration_test -d emulator-5554
